version: "3.3"

services:

  flask:
    build: ./flask
    container_name: flask
    
    environment:
      - APP_NAME=bMRI_analyzer
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    
    ports:
      - "80:80"
